function somar() {
    var num_um = 87;
    var num_dois = 96;
    var total = num_um + num_dois;
    alert ("Valor total da soma entre 87 e 96 é: " + total);
    
    }
    function alerta()
{
alert("SEJA BEM VINDO AO MEU SITE!");
}
function multiplicar() {
    var valor_um = 5;
    var valor_dois = 8;
    var resultado = valor_um * valor_dois;
    alert ("Valor total da multiplicação entre 5 e 8 é: " + resultado);
    
    }
    function arrayCompras(){
    
    var Lista = [
        'Caneca Git',
        'Blusa Reprograma',
        'Caderno',
        'Caneta.',
    ]
    alert(Lista)
    }
